### ISSUE TITLE
Set up editing of pages on the admin site

### ISSUE THREAD

**Issue by RobStallion** [MindAidPrototype/MindAidAdmin#10]

**Comment by shouston3** [comment]
First step is to be able to edit the content of a page, and send that request to the server

**Comment by tas12** [comment]
Users can edit the first section of the about page.  The database is updated with the user's changes. commit 9d1cdbf

**Comment by tas12** [comment]
linking to  issue #45

**Comment by shouston3** [comment]
Issue is too broad, should be a milestone, editing of individual pages will be the issues
