### ISSUE TITLE
Remind page: Do we need this page?

### ISSUE THREAD

**Issue by tas12** [MindAidPrototype/MindAidAdmin#53]

**Comment by tas12** [comment]
I think not

**Comment by shouston3** [comment]
Yea, we don't need it, going to remove

**Comment by tas12** [comment]
We had a call with Helen today. She would like to use the Remind page as a place for teachers to record results of the SDQ. The results would be from students who score amber on the SDQ. Because of this we will need login functionality for teachers as well as storage of manually entered student names and their results. Opened issues 26 and 27 on the MindAidUser repo. Closing issue as we don't need Remind page on the admin side.
